export default [
  { path: '/', redirect: '/welcome' },
  { path: '/welcome', name: '欢迎', icon: 'smile', component: './Welcome' },
  {
    path: '/content',
    name: '内容',
    icon: 'ReadOutlined',
    access: 'canAdmin',
    routes: [
      { path: '/content', redirect: '/content/subject' },
      {
        path: '/content/subject',
        name: '剧集列表',
        component: './Subject',
        parentKeys: ['/content/subject'],
      },
      {
        hideInMenu: true,
        path: '/content/subject/add',
        name: '添加剧集',
        component: './Subject/edit',
        parentKeys: ['/content/subject'],
      },
      {
        hideInMenu: true,
        path: '/content/subject/:id',
        name: '编辑剧集',
        component: './Subject/edit',
        parentKeys: ['/content/subject'],
      },
      {
        path: '/content/feed',
        name: '动态列表',
        component: './404',
        parentKeys: ['/content/feed'],
      },
      {
        hideInMenu: true,
        path: '/content/feed/add',
        name: '添加动态',
        component: './Subject/edit',
        parentKeys: ['/content/feed'],
      },
      {
        hideInMenu: true,
        path: '/content/feed/:id',
        name: '编辑动态',
        component: './Subject/edit',
        parentKeys: ['/content/feed'],
      },
      {
        path: '/content/comment',
        name: '评论列表',
        component: './404',
        parentKeys: ['/content/comment'],
      },
      {
        hideInMenu: true,
        path: '/content/comment/add',
        name: '添加评论',
        component: './Subject/edit',
        parentKeys: ['/content/comment'],
      },
      {
        hideInMenu: true,
        path: '/content/comment/:id',
        name: '编辑评论',
        component: './Subject/edit',
        parentKeys: ['/content/comment'],
      },
      {
        path: '/content/tag',
        name: '标签列表',
        component: './404',
        parentKeys: ['/content/tag'],
      },
      {
        hideInMenu: true,
        path: '/content/tag/add',
        name: '添加标签',
        component: './Subject/edit',
        parentKeys: ['/content/tag'],
      },
      {
        hideInMenu: true,
        path: '/content/tag/:id',
        name: '编辑标签',
        component: './Subject/edit',
        parentKeys: ['/content/tag'],
      },
      {
        path: '/content/attachment',
        name: '附件列表',
        component: './404',
        parentKeys: ['/content/attachment'],
      },
      {
        hideInMenu: true,
        path: '/content/attachment/add',
        name: '添加附件',
        component: './Subject/edit',
        parentKeys: ['/content/attachment'],
      },
      {
        hideInMenu: true,
        path: '/content/attachment/:id',
        name: '编辑附件',
        component: './Subject/edit',
        parentKeys: ['/content/attachment'],
      },
    ],
  },
  {
    path: '/config',
    name: '配置',
    icon: 'setting',
    access: 'canAdmin',
    routes: [
      { path: '/config', redirect: '/config/list' },
      {
        path: '/config/list',
        name: '配置列表',
        icon: 'smile',
        component: './Config/List',
      },
      {
        path: '/config/mcat',
        name: '小分类',
        icon: 'smile',
        component: './Config/Mcat',
      },
      {
        hideInMenu: true,
        path: '/config/mcat/add',
        name: '添加',
        component: './Config/Mcat/edit',
        parentKeys: ['/config/mcat'],
      },
      {
        hideInMenu: true,
        path: '/config/mcat/edit/:id',
        name: '编辑',
        component: './Config/Mcat/edit',
        parentKeys: ['/config/mcat'],
      },
      {
        path: '/config/typelist',
        name: '栏目列表',
        component: './Config/Typelist',
        parentKeys: ['/config/typelist'],
      },
      {
        hideInMenu: true,
        path: '/config/typelist/add',
        name: '添加栏目',
        component: './Config/Typelist/edit',
        parentKeys: ['/config/typelist'],
      },
      {
        hideInMenu: true,
        path: '/config/typelist/edit/:id',
        name: '编辑栏目',
        component: './Config/Typelist/edit',
        parentKeys: ['/config/typelist'],
      },
    ],
  },
  {
    path: '/user',
    name: '用户',
    icon: 'user',
    access: 'canAdmin',
    routes: [
      { path: '/user', redirect: '/user/list' },
      {
        path: '/user/list',
        name: '用户管理',
        component: './User/List',
        parentKeys: ['/user/list'],
      },
      {
        hideInMenu: true,
        path: '/user/add',
        name: '添加用户',
        component: './Subject/edit',
        parentKeys: ['/user/list'],
      },
      {
        hideInMenu: true,
        path: '/user/edit/:id',
        name: '编辑用户',
        component: './Subject/edit',
        parentKeys: ['/content/list'],
      },
    ],
  },
  { name: '表格', icon: 'table', path: '/list', component: './TableList' },
  { path: '/chat', name: 'chat', icon: 'smile', component: './Chat' },
  { hideInMenu: true, path: '/login', layout: false, name: '登录', component: './User/Login' },
  { component: './404' },
];
